# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Brandon Him | Web Developer and Designer
tagline:          'blog'
description:      'A self-taught web developer and designer talking about all great things related to front-end development, and golang.'
url:              http://brandonhim.com
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           Brandon Him
  url:            https://plus.google.com/u/0/+BrandonHim1

paginate:         5

# Custom vars
icon:             https://avatars3.githubusercontent.com/u/6020066?v=3&s=460
cover:            /assets/images/space.jpg

social:
  - icon:         twitter
    url:          https://twitter.com/himbrandon
    desc:         Follow me on twitter

  - icon:         github
    url:          https://github.com/brh55
    desc:         Fork me on github

  - icon:         googleplus-alt
    url:          https://plus.google.com/u/0/+BrandonHim1
    desc:         Add me on google+

  - icon:         linkedin
    url:          https://www.linkedin.com/in/brandon-him-5a194b90
    desc:         Connect with me

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

  - title:        Projects
    url:          /projects

copyright:
  author:         Brandon Him
  url:            http://brandonhim.com
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         true

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
