# Site
name: "Brandon Him"
description: "Developer, Open-sourcer, Passionate Dabbler"
meta_description: "Silicon Valley based developer who is quirky and loves creating things"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
google_analytics: 'UA-46278016-1'

# Authors
authors:
  brandon:
    name: Brandon
    display_name: Him
    gravatar: 49a4f5377b60e3fcc194ca4a9c7ffb00
    email: brandonhim@live.com
    web: https://brandonhim.com
    twitter: https://twitter.com/himbrandon
  
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge